<?php

namespace OC\STBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
class TrickRepository extends \Doctrine\ORM\EntityRepository
{

	public function getTricks($page,$nbPerPages)
	{
         $query = $this->createQueryBuilder('t')
                       ->leftJoin('t.image','i')
                       ->addSelect('i')
                       ->leftJoin('t.video','v')
                       ->addSelect('v')
                       ->getQuery();


          $query->setFirstResult(($page - 1)* $nbPerPages)
               ->setMaxResults($nbPerPages); 
           return new Paginator($query, true);                 
      
	}

	public function getTricksByCategory($category)
	{
		$query = $this->createQueryBuilder('t')
		              ->leftJoin('t.image','i')
		              ->addSelect('i')
		              ->leftJoin('t.categories','cat')
		              ->addSelect('cat')
		              ->where('cat.name = :category ')
		              ->SetParameter('category',$category)
		              ->getQuery()
		              ;

		
		return $query->getResult();              

	}


}
