ocst_homepage:
    path:     /{page}
    defaults:
         _controller: OCSTBundle:Trick:index
         page: 1
    requirements:
         id: \d*     
     

ocst_trick_add:
   path: /trick/add
   defaults: { _controller: OCSTBundle:Trick:add }

ocst_trick_edit:
   path: /trick/edit/{id}
   defaults: { _controller: OCSTBundle:Trick:edit }  
   requirements:
         id: \d+

ocst_trick_delete:
   path: /trick/delete/{id}
   defaults: { _controller: OCSTBundle:Trick:delete }  
   requirements:
         id: \d+  

ocst_trick_view:
   path: /trick/{id}/{page}
   defaults:  
          _controller: OCSTBundle:Trick:view 
          page: 1  
   requirements:
         id: \d+
         page: \d*


ocst_trick_contact:
   path: /contact
   defaults: { _controller: OCSTBundle:Trick:contact }  


ocst_trick_category:
   path: /cat/{category}/{page}
   defaults:  
         _controller: OCSTBundle:Trick:trickCategory 
         page: 1
   requirements:
         page: \d*    

ocst_category_add:
   path: /category/add
   defaults:
        _controller: OCSTBundle:Category:addCategory

ocst_category_view:
   path: /category/list
   defaults:
       _controller: OCSTBundle:Category:view

ocst_category_edit:
   path: /category/edit/{id}
   defaults:
       _controller: OCSTBundle:Category:edit

ocst_category_delete:
  path: /category/delete/{id}
  defaults:
      _controller: OCSTBundle:Category:delete



  
